### ISSUE TITLE
missing /tmp/data01 on pod

### ISSUE THREAD

**Issue by scottdangelo** [IBM/deploy-graph-db-container#3]
I get the following when I deploy OrientDB into the cluster:

```
Error: lstat /tmp/data01: no such file or directory
Error syncing pod
```

I am using the "lite" cluster and have executed
```
$ kubectl apply -f local-volumes.yaml
persistentvolume "pv-volume" created
```

**Comment by shivahr** [comment]
Hi Scott,
Can you please try deleting the persistent volumes (PV) along with any running OrientDB pods/services and then try recreating the PVs and OrientDB pods/services as per below commands. I have noticed the problem "Error: lstat /tmp/data01: no such file or directory. Error syncing pod" when we re-create a service without deleting the previously created/linked PV.

Delete the OrientDB service from your Bluemix Kubernetes cluster:
$ kubectl delete -f orientdb.yaml

Delete your local persistent volume:
$ kubectl delete -f local-volumes.yaml

Create a hostPath PersistentVolume
$ kubectl apply -f local-volumes.yaml

Deploy OrientDB into Kubernetes cluster
$ kubectl apply -f orientdb.yaml

**Comment by scottdangelo** [comment]
I have performed the steps you've recommended and still get the same error:
Error: lstat /tmp/data01: no such file or directory
Error syncing pod

Did the Docker container change in some way, such that the /tmp/data01 file is missing? Or is that created dynamically? Could it be a timing issue around the creation of that file?

**Comment by stevemar** [comment]
@shivahr @scottdangelo For what it's worth, I tried to run this and am getting the same error. I also tried the steps you mentioned earlier in the bug report @shivahr -- no luck.

I notice the error on step 1.5 when I'm asking to launch the orientdb dashboard (it fails to load), and when i launch the kube dashboard I see the same `/tmp/data01` error that @scottdangelo mentioned. I'm also using a _lite_ version of our container service.

Here's the exact log message from the kube admin console.

`"orientdbservice" in pod "orientdbservice-1899052631-l1htv" is waiting to start: lstat /tmp/data01: no such file or director`

The message is not very helpful :(

(Just another side note, the steps were really easy to follow, thanks for that!)
<img width="1185" alt="screen shot 2017-10-15 at 12 40 05 am" src="https://user-images.githubusercontent.com/4118756/31581816-70ebdd30-b141-11e7-814d-b961e06109fd.png">
<img width="1185" alt="screen shot 2017-10-15 at 12 39 33 am" src="https://user-images.githubusercontent.com/4118756/31581817-71099a64-b141-11e7-9c50-cd8b86d6536d.png">

**Comment by shivahr** [comment]
@stevemart @scottdangelo this is now fixed. Bluemix is now using Kubernetes server version 1.7.4 and this needed an additional configuration to be added in local-volumes.yaml `type: DirectoryOrCreate` https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

**Comment by shivahr** [comment]
I have committed the changes to `local-volumes.yaml`. Please run as below:
```
$ kubectl apply -f local-volumes.yaml --validate=false
```

And please run cleanup commands before running above command:
```
$ kubectl delete -f orientdb.yaml
$ kubectl delete -f local-volumes.yaml
```

**Comment by stevemar** [comment]
@shivahr thanks, I was able to go to Step 2. In the future please use PRs so we can test things out and review, too.

**Comment by scottdangelo** [comment]
I still have the issue, despite using a brand new cluster:

 Error: lstat /tmp/data01: no such file or directory
Error syncing pod

**Comment by stevemar** [comment]
reopening at the request of @scottdangelo

**Comment by shivahr** [comment]
I had further discussion with Bluemix Kubernetes team on this. It seems `type: DirectoryOrCreate` will be supported from Kubernetes server version v1.8.x . Until then the safest alternative is to use an existing directory such as `/tmp` as hostPath volume directory.

**Comment by scottdangelo** [comment]
I have tested and this works. Nice job tracking down the bug.
